### ISSUE TITLE
Windows 10 support for Detekt

### ISSUE THREAD

**Issue by ITConsultNYC** [botherder/detekt#69]
I am experiencing difficulties trying to run Detekt on a Windows 10 Pro machine.

I disabled my Internet connections as well as my AV/Firewall software. The utility runs for an extremely long period of time (about an hour) so I wind up cancelling it. I run the utility as Administrator.

I tried running it in Windows 7 compatibility mode to no avail. I tried running it in Windows 8 compatibility mode to no avail.
[logfile.txt](https://github.com/botherder/detekt/files/1164256/logfile.txt)
I attached the log file for your review. I can't decipher what to make of it. Hopefully you can.

Thank you.

PS: If it matters, I have a fast rig: 6th-Gen Core i7 @ 2.60GHz, 16GB DDR4, 512GB NVMe SSD. I also ran it overnight (6+ hours) without any luck. It doesn't error out, just keeps scanning...

**Comment by botherder** [comment]
Detekt is an abandoned project, please don't run it any longer.

**Comment by ITConsultNYC** [comment]
Thanks for the heads up. Is there an alternative to Detekt which is also compatible with Windows 10?

**Comment by ITConsultNYC** [comment]
Hi,

Is there an update to my last question?

Thanks.

**Comment by ITConsultNYC** [comment]
Update?

**Comment by ITConsultNYC** [comment]
Please act professionally and don't ignore me.

**Comment by botherder** [comment]
LOL? I'm not here to provide help desk support.
I have answered to your original question. Detekt is an abandoned project. I have no idea what an alternative would even be.
